vname: History Cards

on:
  push:
    branches: ["main"]
  pull_request:
    types: ["opened", "syncronize", "reopened", "closed"]
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.PROJECT_NAME }}
          directory: ./
